apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-apigw-restapi
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: crossplane-system
    name: in-cluster
  project: demo1
  sources:
    - repoURL: "git@github.com:vispav/crossplane-templates.git"
      path: "aws-api-gateway/rest-api/helm"
      targetRevision: v1.0.2
      helm:
        valueFiles:
        - $values/config/aws-infra.yaml
        - $values/config/apigateway-restapi.yaml
    - repoURL: 'git@github.com:vispav/demo-apps.git'
      targetRevision: main
      ref: values
  syncPolicy:
    automated:      
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=false
  ignoreDifferences:
  - group: '*'
    kind: '*'
    jsonPointers:
    - '/spec/forProvider/tags'